name: StudentAnalysisSystem
options:
  bundleIdPrefix: com.studentanalysis
  deploymentTarget:
    iOS: 18.0
    macOS: 15.0
  createIntermediateGroups: true
  generateEmptyDirectories: true
  
packages:
  LocalPackage:
    path: .

settings:
  base:
    SWIFT_VERSION: 6.0
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    SWIFT_STRICT_CONCURRENCY: complete

targets:
  # macOS App
  StudentAnalysisSystemMac:
    type: application
    platform: macOS
    sources:
      - path: Apps/StudentAnalysisMac
        createIntermediateGroups: true
    dependencies:
      - package: LocalPackage
        products:
          - AnalysisCore
          - StatisticalEngine
          - PredictiveModeling
          - ReportGeneration
          - IndividualLearningPlan
    settings:
      base:
        PRODUCT_NAME: StudentAnalysisSystemMac
        PRODUCT_BUNDLE_IDENTIFIER: com.studentanalysis.mac
        COMBINE_HIDPI_IMAGES: YES
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2025"
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.education
        INFOPLIST_KEY_NSMainStoryboardFile: ""
        INFOPLIST_KEY_NSPrincipalClass: NSApplication

  # iOS App
  StudentAnalysisSystemiOS:
    type: application
    platform: iOS
    sources:
      - path: Apps/StudentAnalysisiOS
        createIntermediateGroups: true
    dependencies:
      - package: LocalPackage
        products:
          - AnalysisCore
          - StatisticalEngine
          - PredictiveModeling
          - ReportGeneration
          - IndividualLearningPlan
    settings:
      base:
        PRODUCT_NAME: StudentAnalysisSystemiOS
        PRODUCT_BUNDLE_IDENTIFIER: com.studentanalysis.ios
        TARGETED_DEVICE_FAMILY: 1,2
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"

schemes:
  StudentAnalysisSystem-Mac:
    build:
      targets:
        StudentAnalysisSystemMac: all
    run:
      config: Debug
      executable: StudentAnalysisSystemMac
    test:
      config: Debug
    archive:
      config: Release

  StudentAnalysisSystem-iOS:
    build:
      targets:
        StudentAnalysisSystemiOS: all
    run:
      config: Debug
      executable: StudentAnalysisSystemiOS
    test:
      config: Debug
    archive:
      config: Release